# Simplified Pre-commit hooks for CRANTpy
# See https://pre-commit.com for more information

repos:
  # Built-in pre-commit hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
        description: Trims trailing whitespace
      - id: end-of-file-fixer
        description: Ensures files end with a newline
      - id: check-yaml
        description: Checks yaml files for parseable syntax
      - id: check-toml
        description: Checks toml files for parseable syntax
      - id: check-json
        description: Checks json files for parseable syntax
      - id: check-added-large-files
        description: Prevents giant files from being committed
        args: ["--maxkb=1000"]
      - id: check-merge-conflict
        description: Checks for files that contain merge conflict strings

  # Import sorting with isort (compatible with Black)
  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        description: Sorts Python imports
        args: [--profile=black, --line-length=88]

  # Black code formatting
  - repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
      - id: black
        description: Formats Python code with Black
        args: [--line-length=88]
        language_version: python3

  # Ruff linting (lenient configuration)
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.9
    hooks:
      - id: ruff
        description: Run Ruff linter
        args: [--fix, --unsafe-fixes]
      - id: ruff-format
        description: Run Ruff formatter

# Configuration for individual hooks
default_language_version:
  python: python3.10

# Global settings
default_stages: [pre-commit]
fail_fast: false

# Exclude patterns for all hooks
exclude: |
  (?x)^(
    .*\.min\.(js|css)$|
    .*\.bundle\.(js|css)$|
    node_modules/.*|
    \.git/.*|
    \.venv/.*|
    __pycache__/.*|
    \.pytest_cache/.*|
    \.mypy_cache/.*|
    dist/.*|
    build/.*
  )$
